language: cpp
os: linux
dist: bionic
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get -y install
        libboost-filesystem-dev
        libboost-program-options-dev
        libfmt-dev
        libfuse3-dev
        libgtest-dev
        libnanomsg-dev
        libspdlog-dev
        libzstd-dev
        fuse3
        python3-nose2
        scons
    - ci/install_flatbuffers.sh
script:
    - ci/run_tests.sh
